name: PR Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  # Quick checks for PR feedback
  quick-checks:
    name: Quick Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Client checks
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - name: Install client dependencies
      run: npm ci
      working-directory: ./client

    - name: Run ESLint
      run: npm run lint
      working-directory: ./client

    - name: Run TypeScript type checking
      run: npm run checkTs
      working-directory: ./client

    - name: Run client unit tests
      run: npm run test -- --run
      working-directory: ./client

    # Server checks
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          server/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('server/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Check Rust formatting
      run: cargo fmt -- --check
      working-directory: ./server

    - name: Run Clippy
      run: cargo clippy -- -D warnings
      working-directory: ./server

    - name: Run Rust tests
      run: cargo test
      working-directory: ./server